services:
  asrserver:
    image: cego1200/asrserver:latest
    container_name: asrserver
    restart: unless-stopped
    ports:
      - "18080:18080"
      - "18081:18081"
      - "18083:18083"
      - "5001:5001"
    volumes:
      - ./data:/data
